"""
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
"""

import collections


# # HashMap: O(n)
# class Solution:
#     def findTheDifference(self, s: str, t: str) -> str:
#         cntMap1 = collections.defaultdict(lambda: 0)
#         cntMap2 = collections.defaultdict(lambda: 0)
        
#         for c in s:
#             cntMap1[c] += 1
            
#         for c in t:
#             cntMap2[c] += 1
#             if cntMap2[c] > cntMap1[c]:
#                 return c
            
#         return ''
        

# Bit manipulation: O(n)
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        ch = 0
        
        for c in s:
            ch ^= ord(c)
            
        for c in t:
            ch ^= ord(c)
            
        return chr(ch)
        

